title: Hello World
author: John
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Some description..

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

---
title: "John Blog Title"
date: 2018-12-12
---
